artifacts_root: artifacts

data_ingestion:
  root_dir: artifacts/data_ingestion # Data Ingestion root folder path
  source_URL: data.zip
  local_data_file: artifacts/data_ingestion/data.zip # Where the file will be stored
  unzip_dir: artifacts/data_ingestion # After unzipping the file we are to save it in this directory

data_validation:
  root_dir: artifacts/data_validation
  unzip_data_dir: artifacts/data_ingestion/data.csv
  STATUS_FILE: artifacts/data_validation/status.txt
  train_data: artifacts/data_validation/train.csv
  test_data: artifacts/data_validation/test.csv

data_transformation:
  root_dir: artifacts/data_transformation
  train_data: artifacts/data_validation/train.csv
  test_data: artifacts/data_validation/test.csv
  trf_train_data: artifacts/data_transformation/train.csv
  trf_test_data: artifacts/data_transformation/test.csv
  preprocessor_obj: artifacts/data_transformation/preprocessor_obj.pkl

model_trainer:
  root_dir: artifacts/model_trainer
  preprocessor_obj: artifacts/data_transformation/preprocessor_obj.pkl
  model_name: artifacts/model_trainer/model.joblib
  train_data: artifacts/data_transformation/train.csv
  test_data: artifacts/data_transformation/train.csv
  fitted_preprocessor_obj: artifacts/model_trainer/preprocessor_obj.pkl

model_evaluation:
  root_dir: artifacts/model_evaluation
  test_data: artifacts/data_transformation/test.csv
  preprocessor_obj: artifacts/model_trainer/preprocessor_obj.pkl
  model: artifacts/model_trainer/model.joblib
  metric_file_name: artifacts/model_evaluation/metrics.json